services:
  - type: web
    name: Report-OIML
    env: python
    region: oregon
    plan: free
    branch: feat/backend-setup
    rootDir: backend
    buildCommand: pip install -r requirements.txt && cd ../frontend && npm ci && npm run build:backend
    startCommand: ./render-start.sh
    envVars:
      - key: DATABASE_URL
        value: sqlite:////opt/render/project/data/data.db
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOW_ANY_LOGIN
        value: "true"
      - key: UPLOAD_DIR
        value: /opt/render/project/data/uploads
      - key: PYTHON_VERSION
        value: 3.12.0
    disk:
      name: app-data
      mountPath: /opt/render/project/data
      sizeGB: 1
